// LeadForm.tsx — React form component cho landing page
// Generated by biz-email-setup
// Tự nhận tên/SĐT/email, validate client-side, POST tới /api/submit

"use client";

import { useState, FormEvent } from "react";

type Status = "idle" | "loading" | "success" | "error";

export default function LeadForm() {
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [email, setEmail] = useState("");
  const [status, setStatus] = useState<Status>("idle");
  const [errorMsg, setErrorMsg] = useState("");

  async function handleSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setStatus("loading");
    setErrorMsg("");

    if (!name.trim() || !phone.trim() || !email.trim()) {
      setStatus("error");
      setErrorMsg("Anh/chị điền đủ giúp em họ tên, SĐT và email nhé.");
      return;
    }

    try {
      const params = new URLSearchParams(window.location.search);
      const utm = {
        utm_source: params.get("utm_source") || undefined,
        utm_campaign: params.get("utm_campaign") || undefined,
      };

      const res = await fetch("/api/submit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name, phone, email, ...utm }),
      });

      const data = await res.json();
      if (!res.ok || !data.ok) {
        setStatus("error");
        setErrorMsg(data.error || "Có lỗi gửi form. Anh/chị thử lại.");
        return;
      }

      setStatus("success");
      setName("");
      setPhone("");
      setEmail("");
    } catch {
      setStatus("error");
      setErrorMsg("Mạng có vẻ chậm. Anh/chị thử lại hoặc nhắn Zalo trực tiếp.");
    }
  }

  if (status === "success") {
    return (
      <div className="rounded-xl bg-green-50 p-6 text-center">
        <p className="text-lg font-semibold text-green-900">✓ Đã nhận thông tin!</p>
        <p className="mt-2 text-sm text-green-800">
          Anh/chị check email (và spam folder) trong 1 phút tới. Có gì cần
          hỗ trợ liên hệ Zalo: <strong>{"{{ZALO_NUMBER}}"}</strong>.
        </p>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-3" noValidate>
      <input
        type="text"
        placeholder="Họ và tên"
        value={name}
        onChange={(e) => setName(e.target.value)}
        required
        autoComplete="name"
        className="w-full rounded-lg border border-gray-300 px-4 py-3 text-base outline-none focus:border-black focus:ring-2 focus:ring-black/10"
      />
      <input
        type="tel"
        placeholder="Số điện thoại"
        value={phone}
        onChange={(e) => setPhone(e.target.value)}
        required
        autoComplete="tel"
        inputMode="tel"
        pattern="[0-9+\s().-]{9,15}"
        className="w-full rounded-lg border border-gray-300 px-4 py-3 text-base outline-none focus:border-black focus:ring-2 focus:ring-black/10"
      />
      <input
        type="email"
        placeholder="Email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        required
        autoComplete="email"
        inputMode="email"
        className="w-full rounded-lg border border-gray-300 px-4 py-3 text-base outline-none focus:border-black focus:ring-2 focus:ring-black/10"
      />

      <button
        type="submit"
        disabled={status === "loading"}
        className="w-full rounded-lg bg-black px-4 py-3 text-base font-semibold text-white transition hover:bg-gray-800 disabled:opacity-60"
      >
        {status === "loading" ? "Đang gửi..." : "{{CTA_BUTTON_TEXT}}"}
      </button>

      {status === "error" && (
        <p className="text-sm text-red-600">⚠️ {errorMsg}</p>
      )}

      <p className="text-xs text-gray-500">
        Em cam kết không spam. Anh/chị có thể hủy đăng ký bất kỳ lúc nào.
      </p>
    </form>
  );
}
